local status, lspsaga = pcall(require, "lspsaga")
if not status then
	return
end

lspsaga.setup({
	symbol_in_winbar = {
		enable = true,
		separator = " › ",
		hide_keyword = false,
		show_file = true,
		folder_level = 1,
		color_mode = false,
		delay = 300,
	},
	callhierarchy = {
		layout = "float",
		keys = {
			edit = "<CR>",
			vsplit = "s",
			split = "h",
			tabe = "t",
			quit = "q",
			shuttle = "[w",
			toggle_or_req = "u",
			close = { "<C-c>k" },
		},
	},
	code_action = {
		num_shortcut = true,
		show_server_name = false,
		extend_gitsigns = false,
		keys = {
			quit = "q",
			exec = "<CR>",
		},
	},
	definition = {
		width = 0.6,
		height = 0.5,
		keys = {
			edit = "<C-c>o",
			vsplit = "<C-c>v",
			split = "<C-c>i",
			tabe = "<C-c>t",
			quit = "q",
			close = { "<C-c>k" },
		},
	},
	diagnostic = {
		show_code_action = false,
		jump_num_shortcut = true,
		max_width = 0.8,
		max_height = 0.6,
		text_hl_follow = true,
		border_follow = true,
		extend_relatedInformation = false,
		show_layout = "float",
		show_normal_height = 10,
		max_show_width = 0.9,
		max_show_height = 0.6,
		diagnostic_only_current = false,
		keys = {
			exec_action = "o",
			quit = { "q", "<ESC>" },
			toggle_or_jump = "<CR>",
			quit_in_show = { "q", "<ESC>" },
		},
	},
	finder = {
		max_height = 0.9,
		left_width = 0.4,
		right_width = 0.5,
		default = "ref+imp",
		methods = {},
		layout = "float",
		filter = {},
		silent = false,
		keys = {
			shuttle = "[w",
			toggle_or_open = "<CR>",
			vsplit = "s",
			split = "i",
			tabe = "t",
			tabnew = "r",
			quit = "q",
			close = { "<C-c>k" },
		},
	},
	hover = {
		max_width = 0.9,
		max_height = 0.8,
		open_link = "gx",
		open_cmd = "!chrome",
	},
	implement = {
		enable = true,
		sign = true,
		virtual_text = true,
		priority = 100,
	},
	lightbulb = {
		enable = true,
		sign = true,
		virtual_text = false,
		debounce = 10,
		sign_priority = 40,
		enable_in_insert = false,
	},
	outline = {
		keys = {
			jump = "<CR>",
			expand_collapse = "o",
			quit = "<ESC>",
		},
	},
	rename = {
		in_select = true,
		auto_save = false,
		project_max_width = 0.5,
		project_max_height = 0.5,
		keys = {
			quit = { "<ESC>", "<C-c>" },
			exec = "<CR>",
			select = "x",
		},
	},
	ui = {
		border = "rounded",
		devicon = true,
		title = false,
		expand = " ",
		collapse = " ",
		code_action = " ",
		actionfix = " ",
		lines = { "╰", "│", "│", "─", "╭" },
		kind = {},
		imp_sign = "󰳛 ",
	},
})
