require("plugins")
require("user.options")
require("user.keymaps")
require("user.themes.tokyonight")
-- require("user.themes.custom")
-- require("utils")

require("plugins.impatient")
require("plugins.nvimtree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.neoscroll")
require("plugins.comment")
require("plugins.colorizer")
require("plugins.dashboard")
require("plugins.illuminate")
require("plugins.indent-blankline")
require("plugins.autopairs")
require("plugins.multiple-cursors")
require("plugins.zen-mode")
require("plugins.toggleterm")
require("plugins.telescope")
require("plugins.blamer")
require("plugins.hop")
require("plugins.code-runner")
require("plugins.trouble")
require("plugins.mini-surround")
-- require("plugins.navic")
-- require("plugins.winbar")
-- require("plugins.whichkey")
