require("user.options")
require("user.vscode.vs-keymaps")

require("plugins.lsp")
require("plugins")
require("plugins.neoscroll")
require("plugins.comment")
require("plugins.illuminate")
require("plugins.autopairs")
require("plugins.multiple-cursors")
require("plugins.telescope")
require("plugins.hop")
require("plugins.trouble")
require("plugins.mini-surround")