return {
	lsp = {
		Text = " ",
		Method = " ",
		Function = " ",
		Constructor = " ",
		Field = " ",
		Variable = " ",
		Class = " ",
		Interface = " ",
		Module = " ",
		Property = " ",
		Unit = " ",
		Value = " ",
		Enum = " ",
		EnumMember = " ",
		Keyword = " ",
		Snippet = " ",
		Color = " ",
		File = " ",
		Reference = " ",
		Folder = " ",
		Constant = " ",
		Struct = "  ",
		Event = " ",
		Operator = " ",
		TypeParameter = " ",
		Array = " ",
		Number = " ",
		String = " ",
		Boolean = " ",
		Object = " ",
		Package = " ",
	},
	-- arrows
	left_arrow = "",
	right_arrow = "",
	right_arrow_a = "➩ ",
	left_arrow_bold = "",
	right_arrow_bold = "",
	left_arrow_bold_b = "◀",
	right_arrow_bold_b = "▶",
	left_arrow_bold_b_thin = "❮",
	right_arrow_bold_b_thin = "❯",
	chevron_right = ">",
	arrow_closed = "",
	arrow_open = "",
	left_parenthesis_upperhook = "⎛",
	right_parenthesis_upperhook = "⎞",
	right_ceiling = "⌉",
	left_ceiling = "",

	-- borders
	border_up_left = "╭",
	border_up_right = "╮",
	border_down_left = "╰",
	border_down_right = "╯",
	border_horizontal = "─",
	border_vertical = "│",

	-- geometrics
	right_half_ball = "",
	left_half_ball = "",
	ball = " ",
	circle = " ",
	circlebox = "󱔀 ",
	circlebox_outline = "󱗜 ",
	circle_double = "󰺕 ",
	circle_dot = " ",
	circle_slash = " ",
	mod = " ",
	dots_circle = "󱥸",
	hexagon = "󰫈",
	star_circle = "󰦤",

	-- icons
	github = " ",
	github_copilot = " ",
	evilline = " ",
	icon_lualine = " ",
	robot = "ﮧ ",
	git = " ",
	vim = " ",
	cat = "󰄛 ",
	terminal = " ",
	terminal_outline = " ",
	terminal_bash = " ",

	-- git
	added = " ",
	modified = "柳",
	removed = " ",
	branch = " ",

	-- diagnostic
	error = " ",
	warn = " ",
	info = " ",
	hint = " ",

	-- others
	file = " ",
	separator_bold = "▊",
	lock = " ",
	close = "",
	newFile = " ",
	search_left = " ",
	search_right = " ",
	lightbulb = "",
	project = " ",
	dashboard = " ",
	history = " ",
	comment = " ",
	bug = " ",
	code = " ",
	telescope = " ",
	gear = " ",
	package = " ",
	list = " ",
	sign_in = " ",
	sign_out = " ",
	check = " ",
	fire = " ",
	note = " ",
	bookmark = " ",
	pencil = " ",
	table = " ",
	calendar = " ",
	cloud_download = " ",
	eslint = "󰱺 ",
	diamond = " ",
	hexagon_bold = " ",
	hexagon_outline = "󰋙",
	biohazard = " ",
	chemical_weapon = "󰄻",
	snowflake = "󰜗 ",
	hexagon_breakpoint = " ",
	globe = " ",
	cube = " ",

	-- Words
	e_circle_outline = "Ⓔ ",
	x_circle_outline = "Ⓧ ",
	p_circle_outline = "Ⓟ ",
	l_circle_outline = "Ⓛ ",
	o_circle_outline = "Ⓞ ",
	r_circle_outline = "Ⓡ ",

	e_circle = "🅔 ",
	x_circle = "🅧 ",
	p_circle = "🅟 ",
	l_circle = "🅛 ",
	o_circle = "🅞 ",
	r_circle = "🅡 ",

	e_square = "🅴 ",
	x_square = "🆇 ",
	p_square = "🅿 ",
	l_square = "🅻 ",
	o_square = "🅾 ",
	r_square = "🆁 ",

	e_square_outline = "🄴 ",
	x_square_outline = "🅇 ",
	p_square_outline = "🄿 ",
	l_square_outline = "🄻 ",
	o_square_outline = "🄾 ",
	r_square_outline = "🅁 ",
}

-- ================== More Icons ==================
-- Add = "   ",
-- ArrowClosed = " ",
-- ArrowOpen = " ",
-- Array = "    ",
-- Boolean = "蘒  ",
-- Bug = "   ",
-- BigCircle = "   ",
-- BigUnfilledCircle = "   ",
-- Border = {"▄","▄","▄","█","▀","▀","▀","█"},
-- BookMark = " ",
-- ChevronRight = "  > › ",
-- Check = "   ",
-- Calendar = "   ",
-- CloudDownload = "   ",
-- CircuitBoard = "   ",
-- Constructor = "     ",
-- Class = "ﴯ   ",
-- Color = "   ",
-- Constant = "   ",
-- Circle = "   ",
-- Close = "  ",
-- Circle_slash = " ",
-- Circle_dot = " "
-- Circlebox = "󱔀 ",
-- Circlebox_outline = "󱗜 ",
-- Circle_double = "󰺕 "
-- Comment = "   ",
-- Code = "   ",
-- Dashboard = "   ",
-- Dots_square = "
-- Diamond = " "
-- Diff = "   ",
-- Eslint = "  󰱺",
-- Error = "   ",
-- Enum = "   ",
-- Event = "  ",
-- EnumMember = "   ",
-- Field = " ",
-- Folder = "     ",
-- Function = "  󰡱     ",
-- File = "    ",
-- Files = "   ",
-- Fire = "   ",
-- Github = "     ",
-- Gear = "   ",
-- History = "   ",
-- Hint = "   ",
-- Hexagon = "󰫈 ",
-- Interface = "   ",
-- Ignore = "   ",
-- Keyword = "     ",
-- Lsp = " ",
-- Lock = "   ",
-- Lightbulb = "   ",
-- List = "   ",
-- Method = "m    ",
-- Misc = " ",
-- Module = "    ",
-- Mod = "   ",
-- NoteBook = " ",
-- Number = "   ",
-- NewFile = "   ",
-- Note = "   ",
-- Operator = "   ",
-- Object = "  ",
-- OpenFolder = "   ",
-- Octoface = "   "
-- Property = "  ",
-- Project = "   ",
-- Package = "     ",
-- Pencil = "   ",
-- Question = "   ",
-- Reference = "     ",
-- Remove = "   ",
-- Rename = "    ",
-- Repo = "   ",
-- Robot = "ﮧ  ",
-- Snippet = "      ",
-- Struct = "   ",
-- String = " ",
-- Squirrel = "   ",
-- SignIn = "   ",
-- SignOut = "   ",
-- Search = "   ",
-- Smiley = "ﲃ  ",
-- TypeParameter = "     ",
-- Table = "   ",
-- Information = "   ",
-- Telescope = "   ",
-- Tag = "   ",
-- Text = "   ",
-- Unit = "塞    ",
-- Value = "   ",
-- Variable = "   ",
-- Warning = "   ",
-- Watch = "   ",
-- Wordpress = "  ",

--      פּ  ﯟ       蘒練       some other good icons

-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet