return {
	-- Themes
	-- "rebelot/kanagawa.nvim",
	-- "folke/tokyonight.nvim",
	-- "Mofiqul/vscode.nvim",
	-- "overcache/NeoSolarized",
	-- { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	-- "morhetz/gruvbox",
	-- "navarasu/onedark.nvim",
	-- "drewtempelmeyer/palenight.vim",
	-- "lunarvim/darkplus.nvim",

	-- Telescope and finders
	-- "nvim-telescope/telescope.nvim",
	-- "nvim-telescope/telescope-ui-select.nvim",
	-- "nvim-telescope/telescope-media-files.nvim",
	-- "nvim-lua/plenary.nvim",
	-- "nvim-lua/popup.nvim",
	-- "nvim-pack/nvim-spectre",

	-- Nvimtree, lualine and bufferline
	-- "kyazdani42/nvim-tree.lua",
	-- "kyazdani42/nvim-web-devicons",
	-- "akinsho/bufferline.nvim",
	-- "nvim-lualine/lualine.nvim",

	--Treesitter and code colors
	-- {
	-- 	"nvim-treesitter/nvim-treesitter",
	-- 	build = function()
	-- 		pcall(require("nvim-treesitter.install").update({ with_sync = true }))
	-- 	end,
	-- 	dependencies = {
	-- 		"nvim-treesitter/nvim-treesitter-textobjects",
	-- 	},
	-- },
	-- { "m-demare/hlargs.nvim", dependencies = "nvim-treesitter/nvim-treesitter" },
	-- "windwp/nvim-ts-autotag",
	-- "windwp/nvim-autopairs",
	-- "HiPhish/rainbow-delimiters.nvim",
	-- "norcalli/nvim-colorizer.lua",
	-- "lukas-reineke/indent-blankline.nvim",
	-- "RRethy/vim-illuminate",

	-- Lsp
	-- "neovim/nvim-lspconfig",
	-- "onsails/lspkind-nvim",
	-- "ray-x/lsp_signature.nvim",
	-- "tamago324/nlsp-settings.nvim",
	-- "jose-elias-alvarez/nvim-lsp-ts-utils",
	-- "jose-elias-alvarez/null-ls.nvim",
	-- "jose-elias-alvarez/typescript.nvim",
	-- "hrsh7th/nvim-cmp",
	-- "hrsh7th/cmp-nvim-lsp",
	-- "hrsh7th/cmp-buffer",
	-- "hrsh7th/cmp-path",
	-- "hrsh7th/cmp-cmdline",
	-- "l3MON4D3/luasnip",
	-- "rafamadriz/friendly-snippets",
	-- "saadparwaiz1/cmp_luasnip",
	-- "williamboman/nvim-lsp-installer",
	-- "williamboman/mason-lspconfig.nvim",
	-- { "williamboman/mason.nvim", build = ":MasonUpdate" },
	-- { "nvimdev/lspsaga.nvim", dependencies = "nvim-lspconfig" },
	-- { "tzachar/cmp-tabnine", build = "./install.sh", dependencies = "hrsh7th/nvim-cmp" },

	-- Git, DAP and Comments
	-- "APZelos/blamer.nvim",
	-- "lewis6991/gitsigns.nvim",
	-- "numToStr/Comment.nvim",
	-- "theHamsta/nvim-dap-virtual-text",
	-- "JoosepAlviste/nvim-ts-context-commentstring",
	-- { "mfussenegger/nvim-dap" },
	-- { "rcarriga/nvim-dap-ui", dependencies = { "mfussenegger/nvim-dap" } },
	-- { "folke/todo-comments.nvim", dependencies = "nvim-lua/plenary.nvim" },

	-- UI
	-- "petertriho/nvim-scrollbar",
	-- "folke/zen-mode.nvim",
	-- "folke/twilight.nvim",
	-- "anuvyklack/pretty-fold.nvim",
	-- "karb94/neoscroll.nvim",
	-- { "phaazon/hop.nvim", branch = "v1" },

	-- Others
	-- "stevearc/dressing.nvim",
	-- "akinsho/toggleterm.nvim",
	-- "folke/which-key.nvim",
	-- "iamcco/markdown-preview.nvim",
	-- { "folke/trouble.nvim", cmd = "TroubleToggle" },
	-- { "mg979/vim-visual-multi", branch = "master" },
	-- { "CRAG666/code_runner.nvim", dependencies = "nvim-lua/plenary.nvim" },
	-- { "echasnovski/mini.nvim", branch = "stable" },
}
